In [46]:
# Importação bibliotecas
!pip install selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

Requirement already satisfied: selenium in c:\users\joyce\anaconda3\lib\site-packages (4.3.0)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\joyce\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\joyce\anaconda3\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\joyce\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: async-generator>=1.9 in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: idna in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sortedcontainers in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: outcome in c:\users\joyce\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: pycparser in c:\users\joyce\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\joyce\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\joyce\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.8)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\joyce\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (21.0.0)
Requirement already satisfied: certifi in c:\users\joyce\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\joyce\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: six>=1.5.2 in c:\users\joyce\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\joyce\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [47]:
#Passo 1: Copiar informações do site.

# Abrir o navegador 
navegador = webdriver.Chrome()
# Entrar no Google ou Site
navegador.get("https://google.com.br/")

# Pesquisar Dolar §Comands:.send_keys():'escrever no elemento' .click():'clicar no elemento' .get_attribute(): 'pegar informações do elemento'§

navegador.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input' ).send_keys("cotacao dolar")
navegador.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input' ).send_keys(Keys.ENTER)
# Copiar informação
Cotacao_Dolar = navegador.find_element('xpath','//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')

# Pesquisar Euro

navegador.get("https://google.com.br/")
navegador.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input' ).send_keys("cotacao euro")
navegador.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input' ).send_keys(Keys.ENTER)
Cotacao_Euro = navegador.find_element('xpath','//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value')

# Pesquisar Ouro

navegador.get("https://www.melhorcambio.com/ouro-hoje")
Cotacao_Ouro = navegador.find_element('xpath', '//*[@id="comercial"]').get_attribute("value")
Cotacao_Ouro = Cotacao_Ouro.replace(",", ".")
print(Cotacao_Dolar)
print(Cotacao_Euro)
print(Cotacao_Ouro)

navegador.quit()

5.1728
5.280140772
296.33

In [48]:
import pandas as pd
#Passo 2: Importar banco de dados no excel
tabela = pd.read_excel("Banco_Dados_Teste.xlsx")
display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

In [49]:
#Passo 3: Atualizar Banco de Dados

# Substituir dados tabela.l]=="Dolar", "Cotacao") = float(informacao01)oc(linha, coluna) = float§numero decimal§(informacao01)
tabela.loc[tabela["Moeda"] == "Dólar", "Cotação"] = float(Cotacao_Dolar)
tabela.loc[tabela["Moeda"] == "Euro", "Cotação"] = float(Cotacao_Euro)
tabela.loc[tabela["Moeda"] == "Ouro", "Cotação"] = float(Cotacao_Ouro)

# atualizar o preço base reais (preço base original * cotação)
tabela["Preço de Compra"] = tabela["Preço Original"] * tabela["Cotação"]

# atualizar o preço final (preço base reais * Margem)
tabela["Preço de Venda"] = tabela["Preço de Compra"] * tabela["Margem"]

# tabela["Preço de Venda"] = tabela["Preço de Venda"].map("R${:.2f}".format)

display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.172800,5172.748272,1.40,7241.847581
1,Carro Renault,4500.00,Euro,5.280141,23760.633474,2.00,47521.266948
2,Notebook Dell,899.99,Dólar,5.172800,4655.468272,1.70,7914.296062
3,IPhone,799.00,Dólar,5.172800,4133.067200,1.70,7026.214240
4,Carro Fiat,3000.00,Euro,5.280141,15840.422316,1.90,30096.802400
5,Celular Xiaomi,480.48,Dólar,5.172800,2485.426944,2.00,4970.853888
6,Joia 20g,20.00,Ouro,296.330000,5926.600000,1.15,6815.590000

In [50]:
#Passo 4: Exportar a base de dados para o excel ou arquivo
tabela.to_excel("Banco_Dados_Teste_V02.xlsx", index=False)